apiVersion: v1
kind: ConfigMap
metadata:
  name: { '{' } include "payment-service.fullname" . { '}' }-config
data:
  NODE_ENV: "{ '{' } .Values.env.NODE_ENV { '}' }"
  LOG_LEVEL: "{ '{' } .Values.env.LOG_LEVEL { '}' }"
  DB_HOST: "{ '{' } .Values.env.DB_HOST { '}' }"
