replicaCount: 1

image:
  repository: "<ACCOUNT_ID>.dkr.ecr.${{AWS_REGION}}.amazonaws.com/REPO"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

env:
  NODE_ENV: production
  LOG_LEVEL: info
  DB_HOST: rds.endpoint
secrets:
  DB_PASSWORD: changeme
  JWT_SECRET: changeme
