apiVersion: v1
kind: Secret
metadata:
  name: { '{' } include "notification-service.fullname" . { '}' }-secrets
type: Opaque
stringData:
  DB_PASSWORD: "{ '{' } .Values.secrets.DB_PASSWORD { '}' }"
  JWT_SECRET: "{ '{' } .Values.secrets.JWT_SECRET { '}' }"
